# Automated Petstore API using Newman CLI

name: Automated Petstore API using Newman CLI
on: workflow_dispatch

jobs:
  run-postman-collection:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Create dir
        run: | 
          mkdir TestArtifact

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install newmen
        run: npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Run Test
        run: newman run "Petstore.postman_collection.json" -e "Petstore.postman_environment.json" -r cli,htmextra --reporter-htmlextra-export testArtifacts/htmlreport.html

      - name: Test Output
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: testArtifacts
